[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "cryptography>=45.0.2",
    "flask>=3.1.1",
    "flask-cors>=6.0.0",
    "python-dotenv>=1.1.0",
    "requests>=2.32.3",
]
